# Generated by Django 5.1.7 on 2025-04-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id'], 'verbose_name_plural': 'Task'},
        ),
    ]
